"""Render Docker Compose files from evaluated Pkl config objects."""

from __future__ import annotations

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq
import io


GENERATED_HEADER = "# Generated by tools/generate_configs.py — DO NOT EDIT\n"


def render_compose(cfg) -> str:
    """Render a docker-compose.yml from the Pkl config model."""
    rt = cfg.runtime
    ct = cfg.container
    cp = cfg.compose
    dep = cfg.deployment

    service = CommentedMap()

    # Build config
    build = CommentedMap()
    build["context"] = "."
    build["dockerfile"] = "Dockerfile"
    build_args = CommentedMap()
    build_args["IBCTL_BUILD_VERSION"] = "${IBCTL_BUILD_VERSION:-}"
    build["args"] = build_args
    service["build"] = build

    service["container_name"] = ct.containerName
    service["restart"] = ct.restartPolicy
    service["oom_score_adj"] = -1000

    # Environment
    env = CommentedMap()
    env["DISPLAY"] = ":1"

    # Auth
    env["TWS_USERID"] = "${TWS_USERID}"
    env["TWS_PASSWORD"] = "${TWS_PASSWORD}"
    env["TWS_USERID_PAPER"] = "${TWS_USERID_PAPER:-}"
    env["TWS_PASSWORD_PAPER"] = "${TWS_PASSWORD_PAPER:-}"

    # Trading mode
    mode = dep.tradingMode
    env["TRADING_MODE"] = f"${{TRADING_MODE:-{mode}}}"

    # 2FA
    env["TWOFACTOR_CODE"] = "${TWOFACTOR_CODE:-}"
    env["TOTP_PROVIDER"] = f"${{TOTP_PROVIDER:-{rt.twofa.provider}}}"
    env["TWOFA_DEVICE"] = "${TWOFA_DEVICE:-}"
    env["TWOFA_TIMEOUT_ACTION"] = (
        f"${{TWOFA_TIMEOUT_ACTION:-{rt.twofa.timeoutAction}}}"
    )
    env["TWOFA_EXIT_INTERVAL"] = (
        f"${{TWOFA_EXIT_INTERVAL:-{int(rt.twofa.exitInterval)}}}"
    )
    env["RELOGIN_AFTER_TWOFA_TIMEOUT"] = "${RELOGIN_AFTER_TWOFA_TIMEOUT:-yes}"

    # API
    env["TWS_ACCEPT_INCOMING"] = (
        f"${{TWS_ACCEPT_INCOMING:-{rt.session.acceptIncoming}}}"
    )
    env["TWS_MASTER_CLIENT_ID"] = "${TWS_MASTER_CLIENT_ID:-}"
    env["READ_ONLY_API"] = "${READ_ONLY_API:-no}"
    env["BYPASS_WARNING"] = "${BYPASS_WARNING:-yes}"
    env["ALLOW_BLIND_TRADING"] = "${ALLOW_BLIND_TRADING:-no}"
    env["TWS_API_INSTRUMENT_TIMEZONE"] = "${TWS_API_INSTRUMENT_TIMEZONE:-UTC format}"

    # Scheduling
    env["AUTO_RESTART_TIME"] = "${AUTO_RESTART_TIME:-09:05 PM}"
    env["TWS_COLD_RESTART"] = "${TWS_COLD_RESTART:-}"

    # Gateway
    env["JAVA_HEAP_SIZE"] = f"${{JAVA_HEAP_SIZE:-{int(rt.gateway.javaHeapSize)}}}"
    env["TZ"] = f"${{TZ:-{dep.timezone}}}"
    env["VNC_SERVER_PASSWORD"] = "${VNC_SERVER_PASSWORD:-}"
    env["RUST_LOG"] = "${RUST_LOG:-ibctl=info}"
    env["IBCTL_LOG_DIR"] = "/opt/ibctl/persist/logs"

    # Command server
    command_server_default = (
        "true" if cp.exposeCommandServer or cp.exposePaperCommandServer else "false"
    )
    env["IBCTL_COMMAND_SERVER_ENABLED"] = (
        f"${{IBCTL_COMMAND_SERVER_ENABLED:-{command_server_default}}}"
    )
    env["IBCTL_COMMAND_HOST"] = "${IBCTL_COMMAND_HOST:-127.0.0.1}"
    env["IBCTL_COMMAND_PORT"] = (
        f"${{IBCTL_COMMAND_PORT:-{int(rt.commandServer.port)}}}"
    )
    env["IBCTL_COMMAND_HOST_PAPER"] = "${IBCTL_COMMAND_HOST_PAPER:-127.0.0.1}"
    env["IBCTL_COMMAND_PORT_PAPER"] = (
        f"${{IBCTL_COMMAND_PORT_PAPER:-{int(rt.commandServer.paperPort)}}}"
    )

    # Dashboard
    dashboard_default = "true" if cp.exposeDashboard else "false"
    env["IBCTL_DASHBOARD_ENABLED"] = (
        f"${{IBCTL_DASHBOARD_ENABLED:-{dashboard_default}}}"
    )
    env["IBCTL_DASHBOARD_PORT"] = (
        f"${{IBCTL_DASHBOARD_PORT:-{int(rt.dashboard.port)}}}"
    )
    env["IBCTL_DASHBOARD_TOKEN"] = "${IBCTL_DASHBOARD_TOKEN:-}"
    env["IBCTL_DASHBOARD_AUTH_SECRET"] = "${IBCTL_DASHBOARD_AUTH_SECRET:-}"
    env["IBCTL_DASHBOARD_EXTERNAL_URL"] = "${IBCTL_DASHBOARD_EXTERNAL_URL:-}"
    env["IBCTL_ROOT_PATH"] = "${IBCTL_ROOT_PATH:-}"
    env["IBCTL_DEBUG_MODE"] = "${IBCTL_DEBUG_MODE:-}"

    # Notifications (empty = TOML default)
    env["IBCTL_NOTIFICATIONS_ENABLED"] = "${IBCTL_NOTIFICATIONS_ENABLED:-}"
    env["IBCTL_NOTIFICATION_CHANNEL"] = "${IBCTL_NOTIFICATION_CHANNEL:-}"
    env["IBCTL_NTFY_URL"] = "${IBCTL_NTFY_URL:-}"
    env["IBCTL_NTFY_TOPIC"] = "${IBCTL_NTFY_TOPIC:-}"
    env["IBCTL_NTFY_TOKEN"] = "${IBCTL_NTFY_TOKEN:-}"
    env["IBCTL_SLACK_WEBHOOK_URL"] = "${IBCTL_SLACK_WEBHOOK_URL:-}"
    env["IBCTL_TELEGRAM_BOT_TOKEN"] = "${IBCTL_TELEGRAM_BOT_TOKEN:-}"
    env["IBCTL_TELEGRAM_CHAT_ID"] = "${IBCTL_TELEGRAM_CHAT_ID:-}"
    # HITL ntfy action URL signing key — secret, injected from Infisical.
    env["IBCTL_NTFY_ACTION_SIGNING_KEY"] = "${IBCTL_NTFY_ACTION_SIGNING_KEY:-}"

    # HITL 2FA backoff knobs (empty = TOML default)
    env["IBCTL_TWOFA_MAX_IMMEDIATE_ATTEMPTS"] = "${IBCTL_TWOFA_MAX_IMMEDIATE_ATTEMPTS:-}"
    env["IBCTL_TWOFA_ON_TIMEOUT"] = "${IBCTL_TWOFA_ON_TIMEOUT:-}"
    env["IBCTL_TWOFA_STRATEGY"] = "${IBCTL_TWOFA_STRATEGY:-}"
    env["IBCTL_TWOFA_INTERVALS_MINUTES"] = "${IBCTL_TWOFA_INTERVALS_MINUTES:-}"
    env["IBCTL_TWOFA_CALLBACK_VALID_HOURS"] = "${IBCTL_TWOFA_CALLBACK_VALID_HOURS:-}"
    env["IBCTL_TWOFA_COUNTER_RESET"] = "${IBCTL_TWOFA_COUNTER_RESET:-}"
    env["IBCTL_TWOFA_STABLE_SECS"] = "${IBCTL_TWOFA_STABLE_SECS:-}"
    env["IBCTL_TWOFA_COLD_RESTART_PREEMPTS_HITL"] = "${IBCTL_TWOFA_COLD_RESTART_PREEMPTS_HITL:-}"
    env["IBCTL_TWOFA_NTFY_SEND_RETRIES"] = "${IBCTL_TWOFA_NTFY_SEND_RETRIES:-}"

    # TCP probe knobs (empty = TOML default)
    env["IBCTL_API_PORT_PROBE_INTERVAL_SECS"] = "${IBCTL_API_PORT_PROBE_INTERVAL_SECS:-}"
    env["IBCTL_API_PORT_PROBE_FAILS_BEFORE_REVOKE"] = "${IBCTL_API_PORT_PROBE_FAILS_BEFORE_REVOKE:-}"

    # Reconnect recovery coordinator (empty = TOML default from [timing.recovery])
    env["IBCTL_RECOVERY_DISABLED"] = "${IBCTL_RECOVERY_DISABLED:-}"
    env["IBCTL_RECOVERY_AGGRESSIVE_MAX_SECS"] = "${IBCTL_RECOVERY_AGGRESSIVE_MAX_SECS:-}"
    env["IBCTL_RECOVERY_BACKOFF_MAX_SECS"] = "${IBCTL_RECOVERY_BACKOFF_MAX_SECS:-}"
    env["IBCTL_RECOVERY_BACKOFF_INTERVAL_SECS"] = "${IBCTL_RECOVERY_BACKOFF_INTERVAL_SECS:-}"
    env["IBCTL_RECOVERY_MIN_SUCCESS_DWELL_SECS"] = "${IBCTL_RECOVERY_MIN_SUCCESS_DWELL_SECS:-}"
    env["IBCTL_RECOVERY_FINGERPRINT_STREAK"] = "${IBCTL_RECOVERY_FINGERPRINT_STREAK:-}"
    env["IBCTL_RECOVERY_FORCE_RESET"] = "${IBCTL_RECOVERY_FORCE_RESET:-}"

    # IB System Status
    env["IBCTL_IB_STATUS_ENABLED"] = "${IBCTL_IB_STATUS_ENABLED:-}"
    env["IB_STATUS_CHECK_INTERVAL"] = (
        f"${{IB_STATUS_CHECK_INTERVAL:-{int(rt.ibSystemStatus.checkIntervalSeconds)}}}"
    )
    env["IB_STATUS_REGION"] = f"${{IB_STATUS_REGION:-{rt.ibSystemStatus.region}}}"

    # ZMQ PUB socket
    env["IBCTL_ZMQ_ENABLED"] = "${IBCTL_ZMQ_ENABLED:-}"
    env["IBCTL_ZMQ_PORT"] = f"${{IBCTL_ZMQ_PORT:-{int(rt.dashboard.zmqPort)}}}"

    # Optional overrides (empty = TOML default)
    env["IBCTL_LOG_LEVEL"] = "${IBCTL_LOG_LEVEL:-}"
    env["IBCTL_ACCEPT_INCOMING"] = "${IBCTL_ACCEPT_INCOMING:-}"
    env["IBCTL_SESSION_ACTION"] = "${IBCTL_SESSION_ACTION:-}"
    env["IBCTL_RESTART_DELAY"] = "${IBCTL_RESTART_DELAY:-}"
    env["IBCTL_RELOGIN_FAILURE_ACTION"] = "${IBCTL_RELOGIN_FAILURE_ACTION:-}"
    env["IBCTL_RELOGIN_ATTEMPTS"] = "${IBCTL_RELOGIN_ATTEMPTS:-}"
    env["IBCTL_LOGIN_TIMEOUT"] = "${IBCTL_LOGIN_TIMEOUT:-}"

    # Site role / failover
    env["IBCTL_SITE_ROLE"] = "${IBCTL_SITE_ROLE:-}"
    env["IBCTL_AUTO_LAUNCH"] = "${IBCTL_AUTO_LAUNCH:-}"

    # Auto-update
    env["IBCTL_AUTO_UPDATE"] = "${IBCTL_AUTO_UPDATE:-}"
    env["IBCTL_VERSION"] = "${IBCTL_VERSION:-latest}"

    service["environment"] = env

    # Volumes
    volumes = CommentedSeq()
    volumes.append(f"{cp.persistVolumeName}:{cp.persistMountPath}")
    service["volumes"] = volumes

    # Ports
    ports = CommentedSeq()
    if cp.exposeLiveApi:
        ports.append(
            f"${{IBCTL_LIVE_API_BIND:-127.0.0.1}}:${{IBCTL_LIVE_API_PORT:-4001}}:"
            f"{int(rt.gateway.liveSocatPort)}"
        )
    if cp.exposePaperApi:
        ports.append(
            f"${{IBCTL_PAPER_API_BIND:-127.0.0.1}}:${{IBCTL_PAPER_API_PORT:-4002}}:"
            f"{int(rt.gateway.paperSocatPort)}"
        )
    if cp.exposeVnc:
        ports.append("${IBCTL_VNC_BIND:-127.0.0.1}:5900:5900")
    if cp.exposeNoVnc:
        ports.append("${IBCTL_VNC_BIND:-127.0.0.1}:6080:6080")
    if cp.exposeCommandServer:
        ports.append(f"127.0.0.1:{int(rt.commandServer.port)}:{int(rt.commandServer.port)}")
    if cp.exposePaperCommandServer:
        ports.append(
            f"127.0.0.1:{int(rt.commandServer.paperPort)}:{int(rt.commandServer.paperPort)}"
        )
    if cp.exposeDashboard:
        # Both sides use the dashboard's actual default listen port.
        ports.append(
            f"${{IBCTL_DASHBOARD_BIND:-127.0.0.1}}:${{IBCTL_DASHBOARD_PORT:-{int(rt.dashboard.port)}}}:"
            f"${{IBCTL_DASHBOARD_PORT:-{int(rt.dashboard.port)}}}"
        )
    service["ports"] = ports
    service["tty"] = True

    # Top-level
    root = CommentedMap()
    services = CommentedMap()
    services[cp.serviceName] = service
    root["services"] = services

    # Named volumes
    named_volumes = CommentedMap()
    named_volumes[cp.persistVolumeName] = None
    root["volumes"] = named_volumes

    yaml = YAML()
    yaml.default_flow_style = False
    yaml.width = 120

    buf = io.StringIO()
    yaml.dump(root, buf)
    return GENERATED_HEADER + buf.getvalue()
